[package]
name = "rogue"
version = "0.1.0"
authors = ["coopersimon <simon.d.cooper@hotmail.co.uk>"]

[dependencies]
#modscript = {git = "https://github.com/coopersimon/modscript"}
modscript = {path = "../modscript"}
serde_json = "1.0"
