// For rendering stuff to screen
// Takes in configuration (generated by scripts & engine) and prints output
// Doesn't communicate with scripting engine at all!
// Output will be text to start, might add tile based 2d later

mod textbox;
mod map;
mod printbox;

use pancurses::Window;
use Coord;

// Coords: 0,0 is top left.

pub trait Render {
    fn render(&mut self, w: &mut Window);
}

pub fn render(w: &mut Window, render_data: &mut Vec<Box<Render>>) {
    w.clear();
    for r in render_data {
        r.render(w);
    }
    w.refresh();
}
