// For rendering stuff to screen
// Takes in configuration (generated by scripts & engine) and prints output
// Doesn't communicate with scripting engine at all!
// Output will be text to start, might add tile based 2d later

fn render(/*render_data*/) {
    
}
